# Generated by Django 4.0.2 on 2022-02-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_stu', models.IntegerField()),
                ('reg_stu', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('tehsil', models.CharField(max_length=30)),
                ('web', models.URLField(blank=True, max_length=100, null=True)),
                ('type', models.IntegerField()),
                ('play_area', models.BooleanField(default=False)),
                ('status_of_property', models.BooleanField(default=False)),
                ('area', models.FloatField()),
                ('total_stu', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='scl_logos/')),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('max_teachers', models.IntegerField()),
                ('reg_teachers', models.IntegerField()),
                ('key', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='user_pics/')),
                ('DOB', models.DateField()),
                ('gender', models.BooleanField(default=True)),
                ('mbl_num', models.CharField(blank=True, max_length=12, null=True)),
                ('religion', models.CharField(max_length=20)),
                ('role', models.IntegerField()),
                ('Con_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('classes', models.ManyToManyField(to='registration.Classes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('G_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=30, null=True)),
                ('roll_num', models.CharField(max_length=3)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.classes')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.teachers')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school')),
            ],
        ),
        migrations.CreateModel(
            name='Scl_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='scl_images/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school')),
            ],
        ),
        migrations.CreateModel(
            name='School_Admins',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('landline', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=25)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.school')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.IntegerField()),
                ('status', models.IntegerField()),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.classes')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.teachers')),
            ],
        ),
    ]
