# Generated by Django 4.0.2 on 2022-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_confcode_remove_user_info_con_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='DOB',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='religion',
            field=models.CharField(default='Islam', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
