# Generated by Django 4.0.2 on 2022-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_user_info_dob_alter_user_info_religion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='DOB',
            field=models.CharField(max_length=10),
        ),
    ]
