# Generated by Django 4.0.2 on 2022-02-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_user_info_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='DOB',
            new_name='Birth_Date',
        ),
    ]
