# Generated by Django 4.0.2 on 2022-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_rename_birth_date_user_info_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
