# Generated by Django 4.0.2 on 2022-02-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_user_info_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='role',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='max_stu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='reg_stu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='key',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='max_teachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='reg_teachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='total_stu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
