# Generated by Django 4.0.2 on 2022-02-12 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_school_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='app_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
