# Generated by Django 4.0.2 on 2022-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_applications_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scl_images',
            name='text',
            field=models.CharField(default='pic1', max_length=5),
        ),
    ]
