# Generated by Django 4.0.2 on 2022-02-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_scl_images_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='key',
            new_name='l_key',
        ),
    ]
