# Generated by Django 4.0.2 on 2022-02-16 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_rename_key_school_l_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(default=datetime.datetime(2022, 2, 16, 10, 58, 43, 233855))),
            ],
        ),
    ]
