# Generated by Django 4.0.2 on 2022-02-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
