# Generated by Django 4.0.2 on 2022-02-16 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.school')),
                ('schedule', models.DateTimeField(default=datetime.datetime(2022, 2, 16, 14, 24, 6, 500924))),
            ],
        ),
    ]
