# Generated by Django 4.0.2 on 2022-02-18 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_user_info_logged_ins_alter_schedule_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 12, 53, 59, 58735)),
        ),
    ]
