# Generated by Django 4.0.2 on 2022-02-19 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_schedule_schedule_alter_teachers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='students',
            name='registered_by',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 13, 4, 17, 728476)),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
