# Generated by Django 4.0.2 on 2022-02-24 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_alter_schedule_schedule_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='G_ID',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 15, 15, 43, 508793)),
        ),
    ]
