# Generated by Django 4.0.2 on 2022-02-25 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_remove_students_g_id_alter_schedule_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 9, 24, 4, 431200)),
        ),
        migrations.AlterField(
            model_name='school',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
