# Generated by Django 4.0.2 on 2022-02-25 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_alter_schedule_schedule_alter_school_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='G_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 9, 59, 27, 135492)),
        ),
    ]
