# Generated by Django 4.0.2 on 2022-03-08 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_students_g_id_alter_schedule_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='app_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='app_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='app_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 13, 21, 35, 348400)),
        ),
    ]
