# Generated by Django 4.0.2 on 2022-03-09 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_school_app_date_students_app_date_teachers_app_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 16, 48, 27, 119641)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='app_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
