# Generated by Django 4.0.2 on 2022-03-08 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_school_app_date_students_app_date_teachers_app_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 14, 18, 47, 565101)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='app_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
