# Generated by Django 4.0.2 on 2022-03-09 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_alter_schedule_schedule_alter_teachers_app_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 16, 49, 5, 999663)),
        ),
    ]
